name: Deploy MultiDocker

on:
  push:
    branches:
      - master  # or 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build images
        run: |
          docker build -t swarnamanjuk/multi-client ./client
          docker build -t swarnamanjuk/multi-nginx ./nginx
          docker build -t swarnamanjuk/multi-server ./server
          docker build -t swarnamanjuk/multi-worker ./worker

      - name: Push images
        run: |
          docker push swarnamanjuk/multi-client
          docker push swarnamanjuk/multi-nginx
          docker push swarnamanjuk/multi-server
          docker push swarnamanjuk/multi-worker
